// Builds supabase/seed/questions.sql and supabase/seed/answer_key.sql (both gitignored)
// from private/assessment_content.mjs. Validates that rubric points add up to each question's max_score
// and that the max scores add up to 100.
//   Usage: npm run seed:generate [-- path/to/content.mjs]
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const contentPath = resolve(process.argv[2] ?? 'private/assessment_content.mjs');
const { assessmentInfo, sections, questions } = await import(pathToFileURL(contentPath).href);

const TAG = '$wt$';
const lit = (s) => {
  if (String(s).includes(TAG)) throw new Error(`Content contains reserved dollar-quote tag ${TAG}`);
  return `${TAG}${s}${TAG}`;
};

const errors = [];
let total = 0;
for (const q of questions) {
  total += q.max_score;
  const pts = q.rubric.reduce((s, r) => s + r.points, 0);
  if (Math.abs(pts - q.max_score) > 1e-9) errors.push(`${q.id}: rubric points ${pts} != max_score ${q.max_score}`);
  if (!sections[q.section]) errors.push(`${q.id}: unknown section ${q.section}`);
  for (const r of q.rubric) {
    for (const p of r.patterns) {
      try { new RegExp(p, 'i'); } catch (e) { errors.push(`${q.id} "${r.label}": bad regex ${p} (${e.message})`); }
    }
  }
}
if (Math.abs(total - 100) > 1e-9) errors.push(`max scores add up to ${total}, expected 100`);
if (errors.length) {
  console.error('Validation failed:\n- ' + errors.join('\n- '));
  process.exit(1);
}

const qSql = [
  '-- GENERATED by scripts/generate-seed.mjs — do not edit or commit.',
  'begin;',
  `insert into public.assessment_info (id, title, intro_md) values (1, ${lit(assessmentInfo.title)}, ${lit(assessmentInfo.intro_md)})`,
  '  on conflict (id) do update set title = excluded.title, intro_md = excluded.intro_md;',
  ...questions.map((q, i) =>
    `insert into public.questions (id, section, section_title, sort_order, title, prompt_md, answer_type, max_score) values (` +
      `'${q.id}', '${q.section}', ${lit(sections[q.section])}, ${i + 1}, ${lit(q.title)}, ${lit(q.prompt_md)}, '${q.answer_type}', ${q.max_score})\n` +
      '  on conflict (id) do update set section = excluded.section, section_title = excluded.section_title, sort_order = excluded.sort_order,\n' +
      '  title = excluded.title, prompt_md = excluded.prompt_md, answer_type = excluded.answer_type, max_score = excluded.max_score;',
  ),
  `delete from public.questions where id not in (${questions.map((q) => `'${q.id}'`).join(', ')});`,
  'commit;',
  '',
].join('\n');

const kSql = [
  '-- GENERATED by scripts/generate-seed.mjs — CONFIDENTIAL, do not commit. Run AFTER questions.sql.',
  'begin;',
  ...questions.map((q) => {
    const rubric = q.rubric.map(({ label, points, patterns, match = 'any', source = 'any' }, idx) => ({
      id: `${q.id}-${idx + 1}`, label, points, patterns, match, source,
    }));
    return `insert into public.answer_key (question_id, model_answer_md, rubric) values ('${q.id}', ${lit(q.model_answer_md)}, ${lit(JSON.stringify(rubric))}::jsonb)\n` +
      '  on conflict (question_id) do update set model_answer_md = excluded.model_answer_md, rubric = excluded.rubric;';
  }),
  'commit;',
  '',
].join('\n');

mkdirSync('supabase/seed', { recursive: true });
writeFileSync('supabase/seed/questions.sql', qSql);
writeFileSync('supabase/seed/answer_key.sql', kSql);

// Also emit a JSON copy used by the local marking unit test (private/, gitignored).
writeFileSync('private/answer_key.generated.json', JSON.stringify(questions.map((q) => ({
  id: q.id, max_score: q.max_score, answer_type: q.answer_type, model_answer_md: q.model_answer_md,
  rubric: q.rubric.map((r, idx) => ({ id: `${q.id}-${idx + 1}`, match: 'any', source: 'any', ...r })),
})), null, 1));

console.log(`OK: ${questions.length} questions, total ${total} marks.`);
console.log('Wrote supabase/seed/questions.sql and supabase/seed/answer_key.sql');
